/*
 * This file is generated by jOOQ.
 */
package uk.co.tyke.travellog.journey.data.postgres.jooq.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.tyke.travellog.journey.data.postgres.jooq.tables.Location;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationRecord extends UpdatableRecordImpl<LocationRecord> implements Record6<Long, Long, BigDecimal, BigDecimal, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>travellog_journey_dev_schema.location.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>travellog_journey_dev_schema.location.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>travellog_journey_dev_schema.location.leg_id</code>.
     */
    public void setLegId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>travellog_journey_dev_schema.location.leg_id</code>.
     */
    public Long getLegId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>travellog_journey_dev_schema.location.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>travellog_journey_dev_schema.location.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>travellog_journey_dev_schema.location.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>travellog_journey_dev_schema.location.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>travellog_journey_dev_schema.location.altitude</code>.
     */
    public void setAltitude(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>travellog_journey_dev_schema.location.altitude</code>.
     */
    public Integer getAltitude() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>travellog_journey_dev_schema.location.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>travellog_journey_dev_schema.location.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, BigDecimal, BigDecimal, Integer, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, BigDecimal, BigDecimal, Integer, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Location.LOCATION.LOCATION_ID;
    }

    @Override
    public Field<Long> field2() {
        return Location.LOCATION.LEG_ID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Location.LOCATION.LATITUDE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Location.LOCATION.LONGITUDE;
    }

    @Override
    public Field<Integer> field5() {
        return Location.LOCATION.ALTITUDE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Location.LOCATION.CREATED;
    }

    @Override
    public Long component1() {
        return getLocationId();
    }

    @Override
    public Long component2() {
        return getLegId();
    }

    @Override
    public BigDecimal component3() {
        return getLatitude();
    }

    @Override
    public BigDecimal component4() {
        return getLongitude();
    }

    @Override
    public Integer component5() {
        return getAltitude();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public Long value1() {
        return getLocationId();
    }

    @Override
    public Long value2() {
        return getLegId();
    }

    @Override
    public BigDecimal value3() {
        return getLatitude();
    }

    @Override
    public BigDecimal value4() {
        return getLongitude();
    }

    @Override
    public Integer value5() {
        return getAltitude();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public LocationRecord value1(Long value) {
        setLocationId(value);
        return this;
    }

    @Override
    public LocationRecord value2(Long value) {
        setLegId(value);
        return this;
    }

    @Override
    public LocationRecord value3(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    @Override
    public LocationRecord value4(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    @Override
    public LocationRecord value5(Integer value) {
        setAltitude(value);
        return this;
    }

    @Override
    public LocationRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public LocationRecord values(Long value1, Long value2, BigDecimal value3, BigDecimal value4, Integer value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationRecord
     */
    public LocationRecord() {
        super(Location.LOCATION);
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(Long locationId, Long legId, BigDecimal latitude, BigDecimal longitude, Integer altitude, LocalDateTime created) {
        super(Location.LOCATION);

        setLocationId(locationId);
        setLegId(legId);
        setLatitude(latitude);
        setLongitude(longitude);
        setAltitude(altitude);
        setCreated(created);
        resetChangedOnNotNull();
    }
}
