/*
 * This file is generated by jOOQ.
 */
package uk.co.tyke.travellog.journey.db.postgres.jooq;


import uk.co.tyke.travellog.journey.db.postgres.jooq.tables.Journey;
import uk.co.tyke.travellog.journey.db.postgres.jooq.tables.Trip;
import uk.co.tyke.travellog.journey.db.postgres.jooq.tables.TripPoint;


/**
 * Convenience access to all tables in travellog_journey_dev_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>travellog_journey_dev_schema.journey</code>.
     */
    public static final Journey JOURNEY = Journey.JOURNEY;

    /**
     * The table <code>travellog_journey_dev_schema.trip</code>.
     */
    public static final Trip TRIP = Trip.TRIP;

    /**
     * The table <code>travellog_journey_dev_schema.trip_point</code>.
     */
    public static final TripPoint TRIP_POINT = TripPoint.TRIP_POINT;
}
