/*
 * This file is generated by jOOQ.
 */
package uk.co.tyke.travellog.journey.data.postgres.jooq;


import uk.co.tyke.travellog.journey.data.postgres.jooq.tables.Journey;
import uk.co.tyke.travellog.journey.data.postgres.jooq.tables.Leg;
import uk.co.tyke.travellog.journey.data.postgres.jooq.tables.Location;


/**
 * Convenience access to all tables in travellog_journey_dev_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>travellog_journey_dev_schema.journey</code>.
     */
    public static final Journey JOURNEY = Journey.JOURNEY;

    /**
     * The table <code>travellog_journey_dev_schema.leg</code>.
     */
    public static final Leg LEG = Leg.LEG;

    /**
     * The table <code>travellog_journey_dev_schema.location</code>.
     */
    public static final Location LOCATION = Location.LOCATION;
}
