/*
 * This file is generated by jOOQ.
 */
package uk.co.tyke.travellog.journey.data.postgres.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import uk.co.tyke.travellog.journey.data.postgres.jooq.tables.Journey;
import uk.co.tyke.travellog.journey.data.postgres.jooq.tables.Leg;
import uk.co.tyke.travellog.journey.data.postgres.jooq.tables.Location;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TravellogJourneyDevSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>travellog_journey_dev_schema</code>
     */
    public static final TravellogJourneyDevSchema TRAVELLOG_JOURNEY_DEV_SCHEMA = new TravellogJourneyDevSchema();

    /**
     * The table <code>travellog_journey_dev_schema.journey</code>.
     */
    public final Journey JOURNEY = Journey.JOURNEY;

    /**
     * The table <code>travellog_journey_dev_schema.leg</code>.
     */
    public final Leg LEG = Leg.LEG;

    /**
     * The table <code>travellog_journey_dev_schema.location</code>.
     */
    public final Location LOCATION = Location.LOCATION;

    /**
     * No further instances allowed
     */
    private TravellogJourneyDevSchema() {
        super("travellog_journey_dev_schema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Journey.JOURNEY,
            Leg.LEG,
            Location.LOCATION
        );
    }
}
