/*
 * This file is generated by jOOQ.
 */
package uk.co.tyke.travellog.journey.db.postgres.jooq.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import uk.co.tyke.travellog.journey.data.jooq.Keys;
import uk.co.tyke.travellog.journey.data.jooq.TravellogJourneyDevSchema;
import uk.co.tyke.travellog.journey.data.jooq.tables.records.TripPointRecord;
import uk.co.tyke.travellog.journey.db.postgres.jooq.Keys;
import uk.co.tyke.travellog.journey.db.postgres.jooq.TravellogJourneyDevSchema;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TripPoint extends TableImpl<TripPointRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>travellog_journey_dev_schema.trip_point</code>
     */
    public static final TripPoint TRIP_POINT = new TripPoint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TripPointRecord> getRecordType() {
        return TripPointRecord.class;
    }

    /**
     * The column
     * <code>travellog_journey_dev_schema.trip_point.trip_point_id</code>.
     */
    public final TableField<TripPointRecord, Long> TRIP_POINT_ID = createField(DSL.name("trip_point_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>travellog_journey_dev_schema.trip_point.trip_id</code>.
     */
    public final TableField<TripPointRecord, Long> TRIP_ID = createField(DSL.name("trip_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>travellog_journey_dev_schema.trip_point.latitude</code>.
     */
    public final TableField<TripPointRecord, BigDecimal> LATITUDE = createField(DSL.name("latitude"), SQLDataType.NUMERIC(7, 4), this, "");

    /**
     * The column
     * <code>travellog_journey_dev_schema.trip_point.longitude</code>.
     */
    public final TableField<TripPointRecord, BigDecimal> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.NUMERIC(7, 4), this, "");

    /**
     * The column <code>travellog_journey_dev_schema.trip_point.altitude</code>.
     */
    public final TableField<TripPointRecord, Integer> ALTITUDE = createField(DSL.name("altitude"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>travellog_journey_dev_schema.trip_point.created</code>.
     */
    public final TableField<TripPointRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6), this, "");

    private TripPoint(Name alias, Table<TripPointRecord> aliased) {
        this(alias, aliased, null);
    }

    private TripPoint(Name alias, Table<TripPointRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>travellog_journey_dev_schema.trip_point</code>
     * table reference
     */
    public TripPoint(String alias) {
        this(DSL.name(alias), TRIP_POINT);
    }

    /**
     * Create an aliased <code>travellog_journey_dev_schema.trip_point</code>
     * table reference
     */
    public TripPoint(Name alias) {
        this(alias, TRIP_POINT);
    }

    /**
     * Create a <code>travellog_journey_dev_schema.trip_point</code> table
     * reference
     */
    public TripPoint() {
        this(DSL.name("trip_point"), null);
    }

    public <O extends Record> TripPoint(Table<O> child, ForeignKey<O, TripPointRecord> key) {
        super(child, key, TRIP_POINT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TravellogJourneyDevSchema.TRAVELLOG_JOURNEY_DEV_SCHEMA;
    }

    @Override
    public Identity<TripPointRecord, Long> getIdentity() {
        return (Identity<TripPointRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TripPointRecord> getPrimaryKey() {
        return Keys.TRIP_POINT_PKEY;
    }

    @Override
    public List<ForeignKey<TripPointRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRIP_POINT__TRIP_POINT_TRIP_ID_FKEY);
    }

    private transient Trip _trip;

    /**
     * Get the implicit join path to the
     * <code>travellog_journey_dev_schema.trip</code> table.
     */
    public Trip trip() {
        if (_trip == null)
            _trip = new Trip(this, Keys.TRIP_POINT__TRIP_POINT_TRIP_ID_FKEY);

        return _trip;
    }

    @Override
    public TripPoint as(String alias) {
        return new TripPoint(DSL.name(alias), this);
    }

    @Override
    public TripPoint as(Name alias) {
        return new TripPoint(alias, this);
    }

    @Override
    public TripPoint as(Table<?> alias) {
        return new TripPoint(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TripPoint rename(String name) {
        return new TripPoint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TripPoint rename(Name name) {
        return new TripPoint(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TripPoint rename(Table<?> name) {
        return new TripPoint(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, BigDecimal, BigDecimal, Integer, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super Long, ? super BigDecimal, ? super BigDecimal, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super Long, ? super BigDecimal, ? super BigDecimal, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
