ROP DATABASE IF EXISTS TL_DEV;

DROP ROLE IF EXISTS tyke_developer;

CREATE ROLE tyke_developer
   LOGIN;

CREATE DATABASE TL_DEV
   OWNER tyke_developer
   ENCODING 'UTF8'
   LC_COLLATE 'en_US.UTF-8'
   LC_CTYPE 'en_US.UTF-8'
   TABLESPACE pg_default
   ALLOW_CONNECTIONS TRUE
   CONNECTION LIMIT - 1
   IS_TEMPLATE FALSE
