/*
 * This file is generated by jOOQ.
 */
package uk.co.tyke.travellog.journey.data.postgres.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.tyke.travellog.journey.data.postgres.jooq.Keys;
import uk.co.tyke.travellog.journey.data.postgres.jooq.TravellogJourneyDevSchema;
import uk.co.tyke.travellog.journey.data.postgres.jooq.tables.records.JourneyRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Journey extends TableImpl<JourneyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>travellog_journey_dev_schema.journey</code>
     */
    public static final Journey JOURNEY = new Journey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JourneyRecord> getRecordType() {
        return JourneyRecord.class;
    }

    /**
     * The column <code>travellog_journey_dev_schema.journey.journey_id</code>.
     */
    public final TableField<JourneyRecord, Long> JOURNEY_ID = createField(DSL.name("journey_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>travellog_journey_dev_schema.journey.name</code>.
     */
    public final TableField<JourneyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>travellog_journey_dev_schema.journey.notes</code>.
     */
    public final TableField<JourneyRecord, String> NOTES = createField(DSL.name("notes"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>travellog_journey_dev_schema.journey.thing</code>.
     */
    public final TableField<JourneyRecord, Integer> THING = createField(DSL.name("thing"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>travellog_journey_dev_schema.journey.created</code>.
     */
    public final TableField<JourneyRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Journey(Name alias, Table<JourneyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Journey(Name alias, Table<JourneyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>travellog_journey_dev_schema.journey</code> table
     * reference
     */
    public Journey(String alias) {
        this(DSL.name(alias), JOURNEY);
    }

    /**
     * Create an aliased <code>travellog_journey_dev_schema.journey</code> table
     * reference
     */
    public Journey(Name alias) {
        this(alias, JOURNEY);
    }

    /**
     * Create a <code>travellog_journey_dev_schema.journey</code> table
     * reference
     */
    public Journey() {
        this(DSL.name("journey"), null);
    }

    public <O extends Record> Journey(Table<O> child, ForeignKey<O, JourneyRecord> key) {
        super(child, key, JOURNEY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TravellogJourneyDevSchema.TRAVELLOG_JOURNEY_DEV_SCHEMA;
    }

    @Override
    public Identity<JourneyRecord, Long> getIdentity() {
        return (Identity<JourneyRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<JourneyRecord> getPrimaryKey() {
        return Keys.JOURNEY_PKEY;
    }

    @Override
    public Journey as(String alias) {
        return new Journey(DSL.name(alias), this);
    }

    @Override
    public Journey as(Name alias) {
        return new Journey(alias, this);
    }

    @Override
    public Journey as(Table<?> alias) {
        return new Journey(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Journey rename(String name) {
        return new Journey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Journey rename(Name name) {
        return new Journey(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Journey rename(Table<?> name) {
        return new Journey(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super String, ? super String, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super String, ? super String, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
